### ISSUE TITLE
PlayerControler

### ISSUE THREAD

**Issue by ArnaudLcq** [LightBender-Games/OfficialLightBender#3]
Faire les mouvements des joueurs

**Comment by mliatt78** [comment]
Les mouvements des joueurs ont été ajoutés.
Des changements ultérieurs pourront être faits à PlayerController, mais tant qu'il n'y a pas de problème particulier, je ne vois pas l'intérêt de garder cette issue ouverte.

**Comment by ArnaudLcq** [comment]
Les mouvements des joueurs ont été ajoutés.
Des changements ultérieurs pourront être faits à PlayerController, mais tant qu'il n'y a pas de problème particulier, je ne vois pas l'intérêt de garder cette issue ouverte.
